--------------------------------------------------------
--  File created - Sunday-April-20-2025   
--------------------------------------------------------
@C:\Users\sachi\Documents\Project_export_init\COACH_SEQ.sql
@C:\Users\sachi\Documents\Project_export_init\EVENT_SEQ.sql
@C:\Users\sachi\Documents\Project_export_init\MATCH_SEQ.sql
@C:\Users\sachi\Documents\Project_export_init\PLAYER_SEQ.sql
@C:\Users\sachi\Documents\Project_export_init\STADIUM_SEQ.sql
@C:\Users\sachi\Documents\Project_export_init\TEAM_SEQ.sql
@C:\Users\sachi\Documents\Project_export_init\COACH.sql
@C:\Users\sachi\Documents\Project_export_init\EVENT.sql
@C:\Users\sachi\Documents\Project_export_init\MATCH.sql
@C:\Users\sachi\Documents\Project_export_init\PLAYER.sql
@C:\Users\sachi\Documents\Project_export_init\PLAYER_STATS.sql
@C:\Users\sachi\Documents\Project_export_init\STADIUM.sql
@C:\Users\sachi\Documents\Project_export_init\TEAM.sql
@C:\Users\sachi\Documents\Project_export_init\COACH_DATA_TABLE.sql
@C:\Users\sachi\Documents\Project_export_init\EVENT_DATA_TABLE.sql
@C:\Users\sachi\Documents\Project_export_init\MATCH_DATA_TABLE.sql
@C:\Users\sachi\Documents\Project_export_init\PLAYER_DATA_TABLE.sql
@C:\Users\sachi\Documents\Project_export_init\PLAYER_STATS_DATA_TABLE.sql
@C:\Users\sachi\Documents\Project_export_init\STADIUM_DATA_TABLE.sql
@C:\Users\sachi\Documents\Project_export_init\TEAM_DATA_TABLE.sql
@C:\Users\sachi\Documents\Project_export_init\COACH_ID_TRIGGER.sql
@C:\Users\sachi\Documents\Project_export_init\GOAL_EVENT_TRIGGER.sql
@C:\Users\sachi\Documents\Project_export_init\EVENT_ID_TRIGGER.sql
@C:\Users\sachi\Documents\Project_export_init\STADIUM_ID_TRIGGER.sql
@C:\Users\sachi\Documents\Project_export_init\MATCH_ID_TRIGGER.sql
@C:\Users\sachi\Documents\Project_export_init\PLAYER_ID_TRIGGER.sql
@C:\Users\sachi\Documents\Project_export_init\TEAM_ID_TRIGGER.sql
@C:\Users\sachi\Documents\Project_export_init\UPDATE_TEAM_POINTS_TRIGGER.sql
@C:\Users\sachi\Documents\Project_export_init\VALIDATE_EVENT_MINUTE_TRIGGER.sql
@C:\Users\sachi\Documents\Project_export_init\COACH_ID_TRIGGER_1.sql
@C:\Users\sachi\Documents\Project_export_init\EVENT_ID_TRIGGER_1.sql
@C:\Users\sachi\Documents\Project_export_init\GOAL_EVENT_TRIGGER_1.sql
@C:\Users\sachi\Documents\Project_export_init\VALIDATE_EVENT_MINUTE_TRIGGER_1.sql
@C:\Users\sachi\Documents\Project_export_init\MATCH_ID_TRIGGER_1.sql
@C:\Users\sachi\Documents\Project_export_init\UPDATE_TEAM_POINTS_TRIGGER_1.sql
@C:\Users\sachi\Documents\Project_export_init\PLAYER_ID_TRIGGER_1.sql
@C:\Users\sachi\Documents\Project_export_init\STADIUM_ID_TRIGGER_1.sql
@C:\Users\sachi\Documents\Project_export_init\TEAM_ID_TRIGGER_1.sql
@C:\Users\sachi\Documents\Project_export_init\DISTRIBUTE_MATCH_STATS.sql
@C:\Users\sachi\Documents\Project_export_init\GENERATE_GOAL_EVENTS.sql
@C:\Users\sachi\Documents\Project_export_init\SETPLAYERASFULLTIMESTARTER.sql
@C:\Users\sachi\Documents\Project_export_init\COACH_CONSTRAINT.sql
@C:\Users\sachi\Documents\Project_export_init\EVENT_CONSTRAINT.sql
@C:\Users\sachi\Documents\Project_export_init\MATCH_CONSTRAINT.sql
@C:\Users\sachi\Documents\Project_export_init\PLAYER_CONSTRAINT.sql
@C:\Users\sachi\Documents\Project_export_init\PLAYER_STATS_CONSTRAINT.sql
@C:\Users\sachi\Documents\Project_export_init\STADIUM_CONSTRAINT.sql
@C:\Users\sachi\Documents\Project_export_init\TEAM_CONSTRAINT.sql
@C:\Users\sachi\Documents\Project_export_init\EVENT_REFCONSTRAINT.sql
@C:\Users\sachi\Documents\Project_export_init\MATCH_REFCONSTRAINT.sql
@C:\Users\sachi\Documents\Project_export_init\PLAYER_REFCONSTRAINT.sql
@C:\Users\sachi\Documents\Project_export_init\PLAYER_STATS_REFCONSTRAINT.sql
@C:\Users\sachi\Documents\Project_export_init\TEAM_REFCONSTRAINT.sql
